### PR TITLE
Updated to the three tabs version

### PR DESCRIPTION
**Pull request by parlerBinou**
The app is updated to have three tabs visualizing data from three different source tables.

To keep the app use the most recent data, the apps load data from my personal repository, https://github.com/parlerBinou/Shiny-RAIS-longitudinal. 
When a new vintage of the source table is released, I'm going to update the file in my repo, and this app will use the updated data files without creating a PR.
Please let me know if this is not allowed / recommended.

### CODE REVIEW

**Comment by parlerBinou** [comment]
Forgot to add: I tested this on Docker, and it works well.

**Review by ca-scribner — DISMISSED** [review]
Don't see anything that should be barred and users have tested so lgtm

**Comment by ca-scribner** [comment]
@blairdrummond this used to just need one of us to approve right?  looks like we need daaas admins now, do you remember when/where that happened?

**Comment by ca-scribner** [comment]
Sorry for the slow response, took a bit to figure out what happened here.

Turns out that because you've included a `LICENSE.md` file in your dashboard, it means @blairdrummond and I cannot approve the change.  All files named `LICENSE.md` are restricted and require an admin's review (someone above us) :)  

I've raised the question of whether this was intended (I think they meant to just control the top level `/LICENSE.md` in the repo, not **all** files named `LICENSE.md`, but in the interim some quick workarounds are:
1. remove your `LICENSE.md`
2. rename it to anything other than `LICENSE` or `LICENSE.md` (I'm not sure if it is case sensitive so maybe `license.md` is ok maybe not)
3. wait for someone with admin status to approve (might be a while)

If you pick either the first or second, Blair and I can merge this immediately :)

**Comment by parlerBinou** [comment]
No worries, and thank you for following up!

The `LICENSE` came from [the oss template](https://github.com/StatCan/oss-templates).
Didn't know having own `LICENSE.md` has such impacts on the merge.

I just removed `LICENSE` from the `rais-siai` directory.

Thank you!

**Comment by ca-scribner** [comment]
Turns out removing that file wasn't enough (I think because it got changed somewhere in the history, even though we removed it later it still required the daaas-admin review?).  But to get around this problem I've opened #37 which is the exact same as this PR, only squashed to a single commit to hide the add/remove of license.md.  Because I created the PR I now cannot review it, but I've pinged @blairdrummond to get him to review.

Sorry for the delay! :)

**Comment by parlerBinou** [comment]
No worries at all!

Should I - can I? - close this request?

**Comment by ca-scribner** [comment]
I think it will auto close when the other merges, but you can also close it
early

**Pull request closed without merging**
