### PR TITLE
Revised the RAIS_SIAS app to use updated data

### PR DESCRIPTION
**Pull request by parlerBinou**
The table this app is based on was revised this morning.

### CODE REVIEW

**Comment by blairdrummond** [comment]
This has merge conflicts somehow. Do you need to merge in master first?

**Comment by parlerBinou** [comment]
Sorry, how can I do that?
They are simple changes (some lines are replaced) in the file but are flagged as conflicts.

**Comment by parlerBinou** [comment]
They are not flagged as conflicts from my forked repository (when compared against the master branch of this repo).
Did I make some mistakes in creating the PR?

**Comment by ca-scribner** [comment]
Do you have a fresh version of the upstream master?  It might be that your master is out of date (to your previous changes)

I think you'd need something like a `git fetch` (might need something more in there to fetch from the upstream repo rather than from your fork.  I think it would be adding a remote but I'd google for 'github sync fork to origin' and see what they say).  Then you'd need to `git merge` the newly refreshed master into your branch, and then this shouldn't have any conflicts

**Comment by parlerBinou** [comment]
Thanks, I will try that.

**Comment by parlerBinou** [comment]
I resolved the conflicts, and it's ready to be merged.

**Review by ca-scribner — APPROVED** [review]

**Pull request merged**
