### PR TITLE
Update the rais-siai dashboard to the three tab version

### PR DESCRIPTION
**Pull request by ca-scribner**
* updated to the three tabs version
* added links to the source tables.
* load data from the official repo
closes #33

### CODE REVIEW

**Comment by ca-scribner** [comment]
This is a redo of #33 with the license file removed to avoid requiring a daaas-admin review

**Review by blairdrummond — APPROVED** [review]
LGTM!

**Comment by parlerBinou** [comment]
Thanks!

**Comment by parlerBinou** [comment]
Sorry, it's me again.

I find that it doesn't work on the server.
https://shiny.covid.cloud.statcan.ca/rais_siai/en/
https://shiny.covid.cloud.statcan.ca/rais_siai/fr/

It just gives a generic error message that it failed during initialization:
```
An error has occurred
The application failed to start.

The application exited during initialization.
```

Is there any way (for me or you) to see the server's log?
I just tested again by cloning the repo, and it works well in Docker.

**Comment by ca-scribner** [comment]
Wow haven't seen this before.  Odd.  Works locally for me too.

@blairdrummond have you seen this?  Locally the thing works fine, but it chokes when we publish for real [here](https://shiny.covid.cloud.statcan.ca/rais_siai/en/).  Any thoughts on how to debug?

**Comment by parlerBinou** [comment]
Some say it's related to permission: https://github.com/rstudio/shiny-server/issues/153

**Comment by ca-scribner** [comment]
The logs didn't give a ton.  Do you know if anything in here might be the problem?
```
su: ignoring --preserve-environment, it's mutually exclusive with --login
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.0.6     ✔ dplyr   1.0.4
✔ tidyr   1.1.2     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
========================================
circlize version 0.4.12
CRAN page: https://cran.r-project.org/package=circlize
Github page: https://github.com/jokergoo/circlize
Documentation: https://jokergoo.github.io/circlize_book/book/

If you use it in published research, please cite:
Gu, Z. circlize implements and enhances circular visualization
  in R. Bioinformatics 2014.

This message can be suppressed by:
  suppressPackageStartupMessages(library(circlize))
========================================

Warning in load_local_config(translation_csv_config) :
  You didn't specify config translation yaml file. Default settings are used.
Error in multmerge(all_files, sep) : 
  Key translation is not the same in all files.
Calls: runApp ... <Anonymous> -> <Anonymous> -> read_and_merge_csvs -> multmerge
Execution halted
```

The error at the bottom is the only thing I can find

**Comment by parlerBinou** [comment]
The last part shouldn't be there.
I believe the messages are coming from a package I used in the previous version, but the package is removed in this version.
And I'm sure it wasn't there when tested locally.

Is it possible that the files of the previous version remain in the server?
Could you delete the `rais_siai` directory in the server and make a fresh copy from this repo?

**Comment by ca-scribner** [comment]
This is now fixed and should be working fine [here](https://shiny.covid.cloud.statcan.ca/rais_siai/en/).  The problem had nothing to do with the dashboard itself, but occurred due to some problems on how we synced the changes to the server.

Basically our current method does not handle file deletions properly.  So while files were deleted from the repo during this change, those files **were not** deleted from the server itself.  New/updated files in this PR were correct, but alongside them were any files that were deleted in this PR.  Those extra derelict files were what caused the problem. 

We encountered this before in #8.  To fix this for now I just cleaned out the old files myself, but a fix to #8 would prevent this from occurring again.

**Comment by parlerBinou** [comment]
Thank you 👍

**Comment by ca-scribner** [comment]
haha sorry I didn't see you message until after I posted mine.  Glad we came to the same conclusion :D  welcome!

**Pull request merged**
