### PR TITLE
Add cma map

### PR DESCRIPTION
**Pull request by Quang-Vinh**

### CODE REVIEW

**Comment by ca-scribner** [comment]
Expected to need:

sudo apt-get install libjq-dev
sudo apt-get install libprotobuf-dev
sudo apt-get install protobuf-compiler
​sudo apt-get install libcurl4-openssl-dev

sudo apt install libcurl4-openssl-dev libssl-dev libxml2-dev
 
r libraries: cansim, rgdal

**Comment by ca-scribner** [comment]
I'll hopefully have it going today/tomorrow morning

**Comment by ca-scribner** [comment]
closes StatCan/DAaaS#143

**Comment by ca-scribner** [comment]
Good to go as soon as StatCan/Shiny#13 is merged

**Comment by chritter** [comment]
@Quang-Vinh Please follow best practices for PRs (https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests), in particular descriptions. Thanks!

**Comment by ca-scribner** [comment]
Hold merging this PR.  Because of StatCan/shiny#14 if we merge this the dashboard will be broken (unable to download data from cansim)

**Comment by ca-scribner** [comment]
Ok ready to go as soon as Statcan/shiny#13 is merged

**Comment by justbert** [comment]
I'm not comfortable approving this :S I don't know R nor Shiny enough to make any calls.

**Review by blairdrummond — APPROVED** [review]
Looks good to me!

**Pull request merged**
