### PR TITLE
rais_siai: Adding a pop up notice for the transition

### PR DESCRIPTION
**Pull request by parlerBinou**
I added a pop up notice (modal) for the transition to the official dissemination channel, and direct users to the official products.
(In addition to small bug fixes and changes)

### CODE REVIEW

**Comment by parlerBinou** [comment]
Hmm.. conflicts again, I'll work on resolving them.

**Comment by parlerBinou** [comment]
I resolved the conflicts.

**Comment by parlerBinou** [comment]
I found that my commits messed up the IJE app. Sorry, I'll address that.

**Comment by parlerBinou** [comment]
Yes, I confirm that my commits no longer changed files in the IJE app, and they only modify files in the rais_siai app.

**Review by blairdrummond — APPROVED** [review]
LGTM! :-)

**Pull request merged**
