### PR TITLE
Add COVID-19 dashboard

### PR DESCRIPTION
**Pull request by barnzilla**
This dashboard provides data visualization for COVID-19 confirmed cases by age group, based on data from Statcan Table  13-10-0766-01 (https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1310076601).

### CODE REVIEW

**Comment by blairdrummond** [comment]
Thanks Joel, taking a look now. I forgot to mention, the shiny server itself lives over here

https://github.com/StatCan/shiny

So you'll probably also need to make a PR over there to add the dependencies to the PACKAGES list.

Edit: Example PR

https://github.com/StatCan/shiny/pull/5/files

**Comment by barnzilla** [comment]
Sounds great, Blair – I’ll make a PR in the shiny repo shortly.

 

Take care,

Joel

**Review by blairdrummond — APPROVED** [review]

**Comment by blairdrummond** [comment]
@barnzilla Your dashboard should be live as soon as the build of the shiny server finishes!

**Comment by blairdrummond** [comment]
@barnzilla There is some sort of issue... I am looking into it.

```
The following object is masked from ‘package:lubridate’:

    here

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ tibble  2.1.3     ✔ dplyr   0.8.4
✔ tidyr   1.0.2     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.4.0
✔ purrr   0.3.3     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::arrange()         masks plyr::arrange(), plotly::arrange()
✖ lubridate::as.difftime() masks base::as.difftime()
✖ readr::col_factor()      masks scales::col_factor()
✖ purrr::compact()         masks plyr::compact()
✖ dplyr::count()           masks plyr::count()
✖ lubridate::date()        masks base::date()
✖ purrr::discard()         masks scales::discard()
✖ dplyr::failwith()        masks plyr::failwith()
✖ dplyr::filter()          masks plotly::filter(), stats::filter()
✖ plyr::here()             masks lubridate::here()
✖ dplyr::id()              masks plyr::id()
✖ lubridate::intersect()   masks base::intersect()
✖ dplyr::lag()             masks stats::lag()
✖ dplyr::mutate()          masks plyr::mutate(), plotly::mutate()
✖ dplyr::rename()          masks plyr::rename(), plotly::rename()
✖ lubridate::setdiff()     masks base::setdiff()
✖ dplyr::summarise()       masks plyr::summarise(), plotly::summarise()
✖ dplyr::summarize()       masks plyr::summarize()
✖ lubridate::union()       masks base::union()
Error in library("xlsx") : there is no package called ‘xlsx’
Calls: runApp ... sourceUTF8 -> eval -> eval -> ..stacktraceon.. -> library
Execution halted
```

**Comment by barnzilla** [comment]
Thanks, Blair! And thanks for troubleshooting the issue that has emerged.

**Pull request merged**
