### PR TITLE
Updated version of IJE Dashboard

### PR DESCRIPTION
**Pull request by david-wavrock**
Requesting the ije-dashboard folder be updated with the changes made to the app over the last several months. I incorporated these changes in a separate repository on github and merged them into R-dashboards in a single commit. Among the changes included are:

-Addition of a CSS file with custom formatting
-Modifications to the README.md file to update with new information
-Changes throughout the global.r, server.r, and ui.r functions with additions and modifications to all plots
-Changes to some of the data included in the data folder
-Inclusion of plotly library to make all graphs interactive

I checked the list of libraries and there are no new ones that need to be added with this PR. There were outstanding issues with some download links in our last update which we hope to resolve in this one. This version of the app was deployed to a shinyapps.io server and download functions worked OK there, so hoping that it's not an issue with the AAW!

Let me know if any additional information is required. Thank you!

### CODE REVIEW

**Review by YannCoderre — APPROVED** [review]
lgtm

**Comment by ca-scribner** [comment]
hey @david-wavrock, we've pushed this and it *should* be active [here](https://shiny.covid.cloud.statcan.ca/ije-dashboard/), but I'm not seeing the figures show up.  Can you try it out and let us know if things look right to you?

Thanks!

**Comment by david-wavrock** [comment]
> hey @david-wavrock, we've pushed this and it _should_ be active [here](https://shiny.covid.cloud.statcan.ca/ije-dashboard/), but I'm not seeing the figures show up. Can you try it out and let us know if things look right to you?
> 
> Thanks!

Hey @ca-scribner, I was going to ask about this - the figures are not showing up on my browser either, and download links on each tab are not functioning either. I looked at other active dashboards as well and plots do not appear to be loading anywhere else as well.

For reference, this updated version places all plots in a plotly enviornment to make them interactive, which in the most recent iteration only applied to the map on the main page (previously using leaflet), which also didn't load in the final version of the app.

**Comment by ca-scribner** [comment]
well now I'm really confused.  Was just browsing to the site to regenerate some logs and paste them here, and then I see...

image

Is it working for anyone else now?  Maybe it had to restart something

**Comment by david-wavrock** [comment]
It also appears to be working for me as well! The download buttons are still experiencing issues (this is an ongoing thing) but otherwise all of the visualizations seem to be working fine.

We did also have a discussion just now with DAaaS people suggesting that given the possible decommissioning of the dashboard system that we may continue to host the app on shinyapps.io, the verison for which is currently fully functional.

**Comment by ca-scribner** [comment]
Wonder why those download buttons don't work... but yeah if you have it working on shinyapps.io then that's even better!

**Pull request merged**
